export const envs = {
  DATABASE_URL: process.env.DATABASE_URL,
  SECRET_KEY: process.env.SECRET_KEY,
  GITHUB_ID: process.env.GITHUB_ID,
  GITHUB_SECRET: process.env.GITHUB_SECRET,
  NEXTAUTH_URL: process.env.NEXTAUTH_URL,
  MAPBOX_TOKEN: process.env.MAPBOX_TOKEN,
  VAPID_PUBLIC_KEY: process.env.VAPID_PUBLIC_KEY,
  VAPID_PRIVATE_KEY: process.env.VAPID_PRIVATE_KEY,
  WIBU_VAPID_PUBLIC_KEY: process.env.WIBU_VAPID_PUBLIC_KEY,
  WIBU_VAPID_PRIVATE_KEY: process.env.WIBU_VAPID_PRIVATE_KEY,
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
};
